version: 1.2
service:
  subclass: DOCKER_COMPOSE
  name: A cool service
  authors: 
  - name: Andrew Duncan
  description: This is the coolest service, it is very very cool.
  files:
     - docker-compose.yml 
     - README.md
