version: 1.2
service:
  subclass: DOCKER_COMPOSE
  name: A cool service
  authour: Andrew Duncan
  description: |
    This is the coolest service,
    it is very cool.
  files:
     - docker-compose.yml 
     - README.md
